const LOGIN = 'LOGIN';
const LOGIN_REJECTED = 'LOGIN_REJECTED';
const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
const CHANGE_LOGIN_STATUS = 'CHANGE_LOGIN_STATUS';

export { LOGIN, LOGIN_REJECTED, LOGIN_FULFILLED, CHANGE_LOGIN_STATUS };
