const PROJECT_FETCH = 'PROJECT_FETCH';
const PROJECT_FETCH_FULFILLED = 'PROJECT_FETCH_FULFILLED';
const PROJECT_FETCH_REJECTED = 'PROJECT_FETCH_REJECTED';

export { PROJECT_FETCH, PROJECT_FETCH_FULFILLED, PROJECT_FETCH_REJECTED };
