const REGISTER = 'REGISTER';
const REGISTER_REJECTED = 'REGISTER_REJECTED';
const REGISTER_FULFILLED = 'REGISTER_FULFILLED';
const RESET_REGISTER_STATE = 'RESET_REGISTER_STATE';

export { REGISTER, REGISTER_REJECTED, REGISTER_FULFILLED, RESET_REGISTER_STATE };
