const REPORT_FETCH = 'REPORT_FETCH';
const REPORT_FETCH_FULFILLED = 'REPORT_FETCH_FULFILLED';
const REPORT_FETCH_REJECTED = 'REPORT_FETCH_REJECTED';

export { REPORT_FETCH, REPORT_FETCH_FULFILLED, REPORT_FETCH_REJECTED };
