const SCOPE_FETCH = 'SCOPE_FETCH';
const SCOPE_FETCH_FULFILLED = 'SCOPE_FETCH_FULFILLED';
const SCOPE_FETCH_REJECTED = 'SCOPE_FETCH_REJECTED';

export { SCOPE_FETCH, SCOPE_FETCH_FULFILLED, SCOPE_FETCH_REJECTED };
