const TASK_FETCH = 'TASK_FETCH';
const TASK_FETCH_FULFILLED = 'TASK_FETCH_FULFILLED';
const TASK_FETCH_REJECTED = 'TASK_FETCH_REJECTED';

export { TASK_FETCH, TASK_FETCH_FULFILLED, TASK_FETCH_REJECTED };
