const TASK_FETCH = 'TASK_FETCH';
const TASK_FETCH_FULFILLED = 'TASK_FETCH_FULFILLED';
const TASK_FETCH_REJECTED = 'TASK_FETCH_REJECTED';
const TASK_CREATE = 'TASK_CREATE';
const TASK_CREATION_FULFILLED = 'TASK_CREATION_FULFILLED';
const TASK_CREATION_REJECTED = 'TASK_CREATION_REJECTED';

export { TASK_FETCH, TASK_FETCH_FULFILLED, TASK_FETCH_REJECTED,
  TASK_CREATE, TASK_CREATION_FULFILLED, TASK_CREATION_REJECTED,
};
