const START_TIMER = 'START_TIMER';
const STOP_TIMER = 'STOP_TIMER';
const PAUSE_TIMER = 'PAUSE_TIMER';
const RESUME_TIMER = 'RESUME_TIMER';

export { START_TIMER, STOP_TIMER, PAUSE_TIMER, RESUME_TIMER };
